#!/usr/bin/env python3

#Program that displays current date and time
  
import datetime #datetime module

now = datetime.datetime.now() #get current date and time

#display formated date and time
print(f"Current date and time: {now.strftime("%y-%m-%d %H:%M:%S:")}")
